//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftRecord
    {
        public Nullable<int> volunteerId { get; set; }
        public int recordId { get; set; }
        public string teamName { get; set; }
        public System.DateTime startOn { get; set; }
        public Nullable<System.DateTime> endOn { get; set; }
        public System.DateTime createOn { get; set; }
        public string createBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public decimal earnedBucks { get; set; }
        public decimal earnHours { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
