//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public int definitionId { get; set; }
        public string displayName { get; set; }
        public string keyName { get; set; }
        public string keyValue { get; set; }
        public string keyGroup { get; set; }
        public Nullable<int> sequence { get; set; }
    }
}
