//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public EmergencyContact()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int contactId { get; set; }
        public Nullable<int> volunteerId { get; set; }
        public string relationship { get; set; }
        public string emergencyPhone { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string contactName { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
