//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public Volunteer()
        {
            this.constituentCode = "";
            this.gender = "Unknown";
            this.note = "\"\"";
            this.EmergencyContacts = new HashSet<EmergencyContact>();
            this.Locations = new HashSet<Location>();
            this.ShiftRecords = new HashSet<ShiftRecord>();
        }
    
        public int volunteerId { get; set; }
        public string constituentCode { get; set; }
        public string title { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string nickName { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string status { get; set; }
        public string gender { get; set; }
        public string homePhone { get; set; }
        public string cellPhone { get; set; }
        public System.DateTime createOn { get; set; }
        public string createBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> activatedOn { get; set; }
        public Nullable<System.DateTime> deactivatedOn { get; set; }
        public string note { get; set; }
        public string token { get; set; }
        public string email { get; set; }
        public string orientation { get; set; }
        public string transitPass { get; set; }
        public string importID { get; set; }
    
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<ShiftRecord> ShiftRecords { get; set; }
    }
}
