//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int locationId { get; set; }
        public Nullable<int> volunteerId { get; set; }
        public Nullable<int> contactId { get; set; }
        public string locationType { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postalcode { get; set; }
        public string country { get; set; }
    
        public virtual EmergencyContact EmergencyContact { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
