DROP TABLE Definition;
CREATE TABLE Definition (definitionId INT NOT NULL IDENTITY, displayName NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, keyName NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, keyValue NVARCHAR(512) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, keyGroup NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, sequence INT, CONSTRAINT PK_DEFINITION PRIMARY KEY (definitionId));
SET IDENTITY_INSERT Definition ON;
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1, 'Alberta', 'Alberta', 'AB', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (2, 'Beer', 'Beer', 'Beer', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (3, 'Male', 'Male', 'Male', 'Gender', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (4, 'Female', 'Female', 'Female', 'Gender', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (5, 'Activate', 'Activate', 'Activate', 'ActiviteStatus', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (6, 'Home', 'Home', 'Home', 'LocationType', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (7, 'Family', 'Family', 'Family', 'ContactReleationship', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (8, 'Friend', 'Friend', 'Friend', 'ContactReleationship', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (9, 'BucksPerShift', 'BucksPerShift', '4', 'Setting', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (10, 'Agents', 'Agents', 'Agents', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (11, 'Ontario', 'Ontario', 'ON', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (12, 'Quebec', 'Quebec', 'QC', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (13, 'Nova Scotia', 'Nova Scotia', 'NS', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (14, 'New Brunswick', 'New Brunswick', 'NB', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (15, 'Manitoba', 'Manitoba', 'MB', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (16, 'British Columbia', 'British Columbia', 'BC', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (17, 'Prince Edward Island', 'Prince Edward Island', 'PE', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (18, 'Saskatchewan', 'Saskatchewan', 'SK', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (19, 'Newfoundland and Labrador', 'Newfoundland and Labrador', 'NL', 'Province', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (20, 'Mr.', 'Mr.', 'Mr.', 'Title', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (21, 'Ms.', 'Ms.', 'Ms.', 'Title', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (22, 'Mrs.', 'Mrs.', 'Mrs.', 'Title', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1002, 'PlateauHours', 'PlateauHours', '20', 'Setting', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1003, 'HonorMessage', 'HonorMessage', 'Thank You for your Exceptional Service!  You have worked 20 hours at this year’s Festival! Get your Limited Edition Shift Pin as our Thank You to you!', 'Setting', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1004, 'Administration Office', 'Administration Office', 'Administration Office', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1005, 'Box Office', 'Box Office', 'Box Office', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1006, 'Community Engagement', 'Community Engagement', 'Community Engagement', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1007, 'First Aid', 'First Aid', 'First Aid', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1008, 'Friend Raisers', 'Friend Raisers', 'Friend Raisers', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1009, 'Front of House', 'Front of House', 'Front of House', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1010, 'Hosting', 'Hosting', 'Hosting', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1011, 'Information Services', 'Information Services', 'Information Services', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1012, 'KidsFringe', 'KidsFringe', 'KidsFringe', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1013, 'Multimedia', 'Multimedia', 'Multimedia', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1014, 'Perimeter Acess', 'Perimeter Acess', 'Perimeter Acess', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1015, 'Souvenirs', 'Souvenirs', 'Souvenirs', 'Team', 1);
INSERT INTO Definition (definitionId, displayName, keyName, keyValue, keyGroup, sequence) VALUES (1016, 'VHQ/MRT', 'VHQ/MRT', 'VHQ/MRT', 'Team', 1);
DROP TABLE EmergencyContact;
CREATE TABLE EmergencyContact (contactId INT NOT NULL IDENTITY, volunteerId INT, emergencyFirstName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, emergencyLastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, relationship NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, emergencyPhone NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, comment NVARCHAR(2048) COLLATE SQL_Latin1_General_CP1_CI_AS, createDate DATE, CONSTRAINT PK_EMERGENCYCONTACT PRIMARY KEY (contactId));
SET IDENTITY_INSERT EmergencyContact ON;
DROP TABLE Location;
CREATE TABLE Location (locationId INT NOT NULL IDENTITY, volunteerId INT, contactId INT, locationType NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS, address NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, city NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, province NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, postalcode NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, CONSTRAINT PK_LOCATION PRIMARY KEY (locationId));
SET IDENTITY_INSERT Location ON;
DROP TABLE ShiftRecord;
CREATE TABLE ShiftRecord (volunteerId INT, recordId INT NOT NULL IDENTITY, teamName NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, startOn DATETIME NOT NULL, endOn DATETIME, createOn DATETIME NOT NULL, createBy NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, modifiedOn DATETIME NOT NULL, modifiedBy NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, earnedBucks NUMERIC(10,2) NOT NULL, earnHours INT NOT NULL, CONSTRAINT PK_SHIFTRECORD PRIMARY KEY (recordId));
SET IDENTITY_INSERT ShiftRecord ON;
DROP TABLE UserProfile;
CREATE TABLE UserProfile (UserId INT NOT NULL IDENTITY, UserName NVARCHAR(56) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, Email NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS, Phone NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS, FullName NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, Administrator BIT DEFAULT 0, Coordinator BIT DEFAULT 1, PRIMARY KEY (UserId), UNIQUE (UserName));
SET IDENTITY_INSERT UserProfile ON;
INSERT INTO UserProfile (UserName, Email, Phone, FullName) VALUES ('admin', 'huangnoah@gmail.com', '(132) 131-3221', 'Noah Huang');
INSERT INTO UserProfile (UserName, Email, Phone, FullName) VALUES ('debbie', 'debbie.buchynski@fringetheatre.ca', '(123) 456-7878', 'debbie');
UPDATE UserProfile set Administrator = 1 where UserId in (1,2);
DROP TABLE Volunteer;
CREATE TABLE Volunteer (volunteerId INT NOT NULL IDENTITY, constituentCode NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, title NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS, firstName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, lastName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, nickName NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS, birthday DATE, status NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS, gender NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS, homePhone NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS, cellPhone NVARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS, createOn DATETIME NOT NULL, createBy NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, modifiedOn DATETIME NOT NULL, modifiedBy NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS, activatedOn DATETIME, deactivatedOn DATETIME, note NVARCHAR(4000) COLLATE SQL_Latin1_General_CP1_CI_AS, token NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS, email NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS, CONSTRAINT PK_VOLUNTEER PRIMARY KEY (volunteerId));
SET IDENTITY_INSERT Volunteer ON;
DROP TABLE __MigrationHistory;
DROP TABLE webpages_Membership;
CREATE TABLE webpages_Membership (UserId INT NOT NULL, CreateDate DATETIME, ConfirmationToken NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS, IsConfirmed BIT DEFAULT 0, LastPasswordFailureDate DATETIME, PasswordFailuresSinceLastSuccess INT DEFAULT 0 NOT NULL, Password NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, PasswordChangedDate DATETIME, PasswordSalt NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, PasswordVerificationToken NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS, PasswordVerificationTokenExpirationDate DATETIME, PRIMARY KEY (UserId));
SET IDENTITY_INSERT webpages_Membership ON;
INSERT INTO webpages_Membership (UserId, CreateDate, ConfirmationToken, IsConfirmed, LastPasswordFailureDate, PasswordFailuresSinceLastSuccess, Password, PasswordChangedDate, PasswordSalt, PasswordVerificationToken, PasswordVerificationTokenExpirationDate) VALUES (1, '2013-02-15 02:28:12', null, 1, null, 0, 'AK/7H97edwUeIHJF/EG4G2X1Sw6A3jkxpdIPZo/NOsILYeexdwl3W+sDddaJ5D3IVA==', '2013-02-15 02:28:12', '', null, null);
INSERT INTO webpages_Membership (UserId, CreateDate, ConfirmationToken, IsConfirmed, LastPasswordFailureDate, PasswordFailuresSinceLastSuccess, Password, PasswordChangedDate, PasswordSalt, PasswordVerificationToken, PasswordVerificationTokenExpirationDate) VALUES (2, '2013-02-15 02:29:47', null, 1, '2013-03-01 07:16:15', 0, 'ACZLlqZF2DBqS32wxNB7DnI0iexDYqifKxIi3eKZFBVGl3Dn8vEgWY9nVt2/jAFw1Q==', '2013-02-15 02:29:47', '', null, null);
DROP TABLE webpages_OAuthMembership;
CREATE TABLE webpages_OAuthMembership (Provider NVARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, ProviderUserId NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, UserId INT NOT NULL, PRIMARY KEY (Provider, ProviderUserId));
SET IDENTITY_INSERT webpages_OAuthMembership ON;
DROP TABLE webpages_Roles;
CREATE TABLE webpages_Roles (RoleId INT NOT NULL IDENTITY, RoleName NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, PRIMARY KEY (RoleId), UNIQUE (RoleName));
INSERT INTO webpages_Roles (RoleName) VALUES ('Administrator');
INSERT INTO webpages_Roles (RoleName) VALUES ('Coordinator');
INSERT INTO webpages_Roles (RoleName) VALUES ('Volunteer');
DROP TABLE webpages_UsersInRoles;
CREATE TABLE webpages_UsersInRoles (UserId INT NOT NULL, RoleId INT NOT NULL, PRIMARY KEY (UserId, RoleId));
INSERT INTO webpages_UsersInRoles (UserId, RoleId) VALUES (1, 1);
INSERT INTO webpages_UsersInRoles (UserId, RoleId) VALUES (1, 2);
INSERT INTO webpages_UsersInRoles (UserId, RoleId) VALUES (2, 1);
INSERT INTO webpages_UsersInRoles (UserId, RoleId) VALUES (2, 2);
ALTER TABLE EmergencyContact ADD CONSTRAINT FK_EMERGENC_REFERENCE_VOLUNTEE FOREIGN KEY (volunteerId) REFERENCES Volunteer (volunteerId);
ALTER TABLE Location ADD CONSTRAINT FK_LOCATION_REFERENCE_VOLUNTEE FOREIGN KEY (volunteerId) REFERENCES Volunteer (volunteerId);
ALTER TABLE ShiftRecord ADD CONSTRAINT FK_SHIFTREC_RECORDS_VOLUNTEE FOREIGN KEY (volunteerId) REFERENCES Volunteer (volunteerId);
ALTER TABLE webpages_UsersInRoles ADD CONSTRAINT fk_RoleId FOREIGN KEY (RoleId) REFERENCES webpages_Roles (RoleId);
